language: go

go:
  - 1.x

os:
  - linux
  - windows

env:
  global:
    - GO111MODULE=on
    - GOFLAGS="-mod=readonly"
    
go_import_path: github.com/Oppodelldog/checkredirects

script:
  - go list ./... | xargs -n1 -I{} sh -c 'go test -race {}'